version: "3"
services:
  mysql:
    image: mysql:8.0.26
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=root1234!!
    ports:
      - 3306:3306
    volumes:
      - /Users/hongdaeyong/study/db/MYSQL8:/var/lib/mysql
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    container_name: mysql8